[package]
name = "orm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orm_lib = { path = "./../orm_lib"}
postgres = "0.19.7"